# -*- coding: utf-8 -*-
"""task7_4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1G_ipuG-zvBYn5UDEDh28rzJAZHoMLLEn
"""

!pip install -q openai-whisper

from google.colab import files

uploaded = files.upload()

import whisper

model = whisper.load_model("base")

result = model.transcribe(list(uploaded.keys())[0])

print("Transcribed Text:")
print(result["text"])