# -*- coding: utf-8 -*-
"""task2(4).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gUxRRWnNc6UCvQUYE67m3cdce_bh5ykZ
"""

pip install --upgrade transformers

from transformers import pipeline

texts = "Hello Nandita! , How are you?"
pip = pipeline("text-to-speech", model="suno/bark-small")
output = pip(texts)

output

from IPython.display import Audio
Audio(output["audio"], rate=output["sampling_rate"])