# -*- coding: utf-8 -*-
"""task1(4).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oBfqFHmiDIPBTbvXwAgjAcdb5KYnVwCq
"""

!pip install transformers
!pip install torch

from transformers import pipeline

sentiment_analyzer = pipeline("sentiment-analysis", model= "distilbert/distilbert-base-uncased")

texts = [
    "I love playing criket",
    "I hate when Virat kohli misses century"
]
results = sentiment_analyzer(texts)
for result in results:
  print(result)