# -*- coding: utf-8 -*-
"""task 4_4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kvM1MeksgUqdl8zOXNCCV2dAWlJbkLYH
"""

pip install datasets

from datasets import load_dataset
dataset = load_dataset("imdb")
train_data = dataset["train"]
for i in range(10):
    print(train_data[i])